/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expert.system.covid.pkg19;

import java.awt.event.KeyEvent;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author luksorn
 */
public class How_to extends javax.swing.JFrame {

    /**
     * Creates new form Q7
     */
    public How_to() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 180, 60));

        jButton1.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        jButton1.setText("Back to HomePage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 180, 60));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("JasmineUPC", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(1);
        jTextArea1.setText("\tหากคุณมีคล้ายจะเป็น COVID-19 หรือไปสัมผัสกับผู้ที่ติดเชื้อCOVID-19\n\nให้ไปพบแพทย์เพื่อเข้ารับการตรวจเชื้อทันที\n\n\n--> ควรปฏิบัติตัวอย่างไรเมื่อพบว่าตัวเองติดเชื้อ COVID-19\n\t\n\t1. ให้ผู้ป่วยอยู่บ้าน ไม่ออกไปอยู่ในพื้นที่สาธารณะ หลีกเลี่ยงการใช้ระบบ-\n\nขนส่งสาธารณะ เช่นรถเมย์หรือแท็กซี่\n\t\n\t2. แยกตัวออกจากครอบครัวและสัตว์เลี้ยง\n\n\t3. ใช้ห้องน้ำแยกต่างหาก\n\t \n\t4. สวมหน้ากากอนามัยไว้เพื่อป้องกันการติดเชื้อ\n\n\t5.ไม่สัมผัสสัตว์เลี้ยงหรือสัตว์อื่นๆขณะที่ป่วย\n\n\t6.อย่าใช้สิ่งของร่วมกับคนในครอบครัวหรือสัตว์เลี้ยง รวมถึงจานรองน้ำดื่ม\n\nและเครื่องนอนต่างๆ\n\n\t7.ล้างมือบ่อยๆ\n\n\t8.ปิดปากเวลาไอหรือจามด้วยกระดาษทิชชู่\n\n\t9.ทำความสะอาดพื้น ลูกบิดประตู อุปกรณ์ในห้องน้ำหรือโทรศัพท์เป็นประจำ\n\t\t\n\t10.ขอความช่วยเหลือจากแพทย์ทันทีหากอาการแย่ลง\n\n--> ผู้ป่วยต้องใช้เวลาเท่าไหร่ในการกักตัว\n\nหากได้รับการยืนยันหรือสงสัยว่าตนเองติดเชื้อ COVID-19 ผู้ป่วยสามารถกักตัวอยู่\n\nที่บ้านได้ จะหยุดกักตัวก็ต่อเมื่อ\n\n\t1.ไม่มีไข้มาอย่างน้อย 24 ชั่วโมงโดยไม่ใช้ยาลดไข้\n\n               2.อาการต่างๆดีขึ้นอย่างน้อย 10 วันตั้งแต่ได้รับการทดสอบว่าติดเชื้อ \n\nCOVID-19 เป็นครั้งแรก\n\n\t3.ไม่มีอาการเจ็บป่วยตามมาอีก\n\n\t\n\n\n");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 611, 390));

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setFont(new java.awt.Font("JasmineUPC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("       วิธิการปฏิบัติตัวเมื่อพบว่าติดเชื้อ COVID-19");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 610, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expert/system/covid/pkg19/covid19_lg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 610));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 24, 400, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(How_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(How_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(How_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(How_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new How_to().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
