/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expert.system.covid.pkg19;

import javax.swing.JOptionPane;

/**
 *
 * @author luksorn
 */
public class Q6 extends javax.swing.JFrame {

    /**
     * Creates new form Q7
     */
    public Q6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        analyzeButton1 = new javax.swing.JButton();
        analyzeButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        analyzeButton1.setBackground(new java.awt.Color(255, 51, 51));
        analyzeButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        analyzeButton1.setText("Cancle");
        analyzeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(analyzeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 100, 40));

        analyzeButton2.setBackground(new java.awt.Color(51, 204, 0));
        analyzeButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        analyzeButton2.setText("Next>>");
        analyzeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(analyzeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, 40));

        jLabel3.setFont(new java.awt.Font("JasmineUPC", 0, 24)); // NOI18N
        jLabel3.setText("เวลาผู้ป่วยดื่มน้ำ มีอาการเจ็บคอเวลากลืนน้ำหรือไม่");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 40));

        jLabel4.setFont(new java.awt.Font("JasmineUPC", 0, 18)); // NOI18N
        jLabel4.setText("(0 :ไม่มี , 1 :รู้สึกเจ็บคอเล็กน้อย , 2 :รู้สึกเจ็บคออย่างมาก )");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 340, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 480, 290));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("6/12");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expert/system/covid/pkg19/covid19_lg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analyzeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyzeButton1ActionPerformed

    private void analyzeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButton2ActionPerformed
        if((jTextField1.getText().equals("0"))||(jTextField1.getText().equals("1"))||(jTextField1.getText().equals("2"))){
        Q7 q7 = new Q7();
        q7.setVisible(true);
        this.setVisible(false);
       }else{
           JOptionPane.showMessageDialog(this,"กรุณากรอกข้อมูลให้ถูกต้อง");
       }
    }//GEN-LAST:event_analyzeButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Q6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Q6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Q6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Q6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Q6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeButton1;
    private javax.swing.JButton analyzeButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
